# Generated by Django 5.0.8 on 2024-12-28 07:53

import apps.support.models.news
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Foydalanuvchi nomi",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ism"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Familiya"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ism va Familiya",
                    ),
                ),
                (
                    "phone",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Telefon raqam"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbek tili"),
                            ("ru", "Rus tili"),
                            ("en", "Ingliz tili"),
                        ],
                        default="uz",
                        max_length=10,
                        verbose_name="Til",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faolmi")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("user", "Foydalanuvchi"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kod"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Foydalanuvchisi",
                "verbose_name_plural": "Bot Foydalanuvchilari",
                "db_table": "bot_users",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Guruh nomi")),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Guruh URL"
                    ),
                ),
                (
                    "group_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Guruh ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faolmi")),
            ],
            options={
                "verbose_name": "Guruh",
                "verbose_name_plural": "Guruhlar",
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Ism va Familiya"),
                ),
                ("birth_date", models.DateField(verbose_name="Tug'ilgan kun")),
                ("age", models.BigIntegerField(verbose_name="Yosh")),
                ("info", models.TextField(verbose_name="Ma'lumot")),
                ("photo", models.ImageField(upload_to="info", verbose_name="Rasm")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faolmi")),
            ],
            options={
                "verbose_name": "Info",
                "verbose_name_plural": "Infos",
                "db_table": "info",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("content", models.TextField(verbose_name="Maqola")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        validators=[apps.support.models.news.validate_image_size],
                        verbose_name="Rasm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="InfoLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Ma'lumot")),
                ("link", models.URLField(verbose_name="Link")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faolmi")),
                (
                    "info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support.info",
                        verbose_name="Ma'lumot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Info Links",
                "verbose_name_plural": "Info Links",
                "db_table": "info_links",
            },
        ),
    ]
