# Generated by Django 5.0.8 on 2024-12-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Kanal", "verbose_name_plural": "Kanallar"},
        ),
        migrations.AlterField(
            model_name="group",
            name="group_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Kanal ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Kanal nomi"),
        ),
        migrations.AlterField(
            model_name="group",
            name="url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Kanal URL"
            ),
        ),
    ]
