# Generated by Django 5.0.8 on 2024-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_group_options_alter_group_group_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Kanal ID"
            ),
        ),
    ]
