# Generated by Django 5.0.8 on 2024-12-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_alter_group_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["name"],
                "verbose_name": "Kanal",
                "verbose_name_plural": "Kanallar",
            },
        ),
    ]
