# Generated by Django 5.0.8 on 2024-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_alter_group_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                choices=[("CHANNEL", "Kanal"), ("BOT", "Bot")],
                default="CHANNEL",
                max_length=10,
                verbose_name="Kanal turi",
            ),
        ),
    ]
