# Generated by Django 5.0.8 on 2024-12-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_group_group_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Kanal",
                "verbose_name_plural": "Kanallar",
            },
        ),
    ]
