# Generated by Django 5.0.8 on 2024-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_alter_group_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="botusers",
            name="code_get_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Kodni olish vaqti"
            ),
        ),
    ]
